# -*- coding: utf-8 -*-
"""Hospital manegment system using python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FwD-WArrcaS24rP2StJpyNMl1b3Fb1ae
"""

# Parent/ super class for all users
class User:
    def __init__(self, username, password):
        self.username = username
        self.password = password

# child/subclass inheriting from user
class Doctor(User):
    def __init__(self, username, password,name):
        super(). __init__(username, password)
        self.name = name

    # function to view all appointments from file
    def view_appointment(self):
        print("\n °°°°°° Doctor Appointments °°°°°")
        try:
            with open("appointments.txt","r") as file:
                for line in file:
                        print(line.strip()) # show each line appointments
        except FileNotFoundError:
            print("No appointments found.") # if file don't exit

    # function to write perceptions for patient
    def write_perceptions(self):
        patient = input("Enter patient name:")
        perceptions = input("Enter perceptions:")
        with open("perceptions.txt","a") as file:
            file.write(f"{patient},{perceptions}\n") # save perception
        print("Perceptions saved.")

    # function to recommend lab tests for patient
    def recommend_test(self):
        patient = input("Enter patient name:")
        test = input("Enter recommend test :")
        with open("lab reports.txt","a") as file:
            file.write(f"{patient},{test}\n") # save lab test
        print("Test recommendations saved.")

# Patient class inheriting from user
class Patient(User):
    def __init__(self, username, password,name):
        super(). __init__(username, password)
        self.name = name

    # Book appointment with a doctor
    def Book_appointment(self):
        doctor = input("Enter doctor name:")
        date = input("Enter appointment date:")
        with open("appointments.txt","a") as file:
            file.write(f"{doctor},{date}\n") # save appointment
        print("Appointment booked.")

    # save perceptions written by doctor for patient
    def view_perceptions(self):
        print("\n === Your perceptions ===")
        try:
            with open("perceptions.txt","r") as file:
                for line in file:
                    if line.startswith (self.name):
                        print(line.strip()) # show matching perceptions
        except FileNotFoundError:
            print("Perceptions not found.")

    # view lab reports for this patient
    def view_lab_reports(self):
        print("\n === Your lab reports ===")
        try:
            with open("lab reports.txt","r") as file:
                for line in file:
                    if line.startswith (self.name):
                        print(line.strip()) # show matching the lab reports
        except FileNotFoundError:
            print("No reports found.")

    # pay hospital bills
    def pay_pills(self):
        amount = input("Enter payment amount:")
        with open("bills.txt","a") as file:
            file.write(f"{self.name} paid {amount}\n") # save bills
        print("bill paid successfully.")

# class Lab/pharmacy inheriting from user
class Labpharmacy(User):
    # lab test requests from doctor
    def view_test_requests(self):
        print("\n ==== Lab test request ====")
        try:
            with open("lab reports.txt","r") as file:
                print(file.read())
        except FileNotFoundError:
            print("No lab test reports")

    # upload test reports for doctor
    def upload_test_reports(self):
        patient = input("Enter patient name:")
        report = input("Enter test reports:")
        with open("lab reports.txt","a") as file:
            file.write(f"{patient}: {report}\n") # save reports
        print("lab report uploaded successfully")

    # view all perceptions for pharmacy
    def view_perceptions(self):
        print("\n === Perception ===")
        try:
            with open("perceptions.txt","r") as file:
                print(file.read())
        except FileNotFoundError:
            print("No Perception found.")

    # Marked medicines as delivered to patients
    def mark_medicine_deliverd(self):
        patient = input("Enter patient name:")
        medicine = input("Enter delivered medicine:")
        with open("pharmacy_records.txt","a") as file:
            file.write(f"{patient}:{medicine}\n") # save medicine delivery
        print("Patient marks as delivered.")

# Simple users
doctors = [Doctor("doc1","123","Imran")]
lab = Labpharmacy("lab1","123")
patients = []

# ========== Main manu loop ============
while True:
    print("\n ===== Hospital management system =====")
    print("1. Patient registration")
    print("2. Patient login")
    print("3. Doctor login")
    print("4. Lab/Pharmacy login")
    print("5. Exit")

    choice = input("Enter choice (1-5):")

    # Patient registration
    if choice == "1":
        username = input("Enter username:")
        password = input("Enter password:")
        name = input("Enter name:")
        new_patient = Patient(username, password, name)
        patients.append(new_patient)
        print("Patient registered successfully")

    # patient login
    elif choice == "2":
        username = input("Enter username:")
        password = input("Enter password:")
        for p in patients:
            if p.username == username and p.password == password:
                print(f"Welcome,{p.name}!")
                # patient panel
                while True:
                    print("\n1.  Book appointment  \n2. View perception \n3. View lab reports \n4. Pay bills \n5.Logout")
                    choice = input("Enter your choice:")
                    if choice == "1":
                        p.Book_appointment()
                    elif choice == "2":
                        p.view_perceptions()
                    elif choice == "3":
                        p.view_lab_reports()
                    elif choice == "4":
                        p.pay_pills()
                    elif choice == "5":
                        break
                    else:
                        print("Invalid Choice")
                break
            else:
                print("Invalid login")

    # Doctor login
    elif choice == "3":
        username = input("Enter username:")
        password = input("Enter password:")
        for doctor in doctors:
            if doctor.username == username and doctor.password == password:
                print(f"Welcome Dr. {doctor.name}!")
                # Doctor panel
                while True:
                    print("\n1. View appointment \n2. Write perceptions \n3. Recommend tests \n4. Logout")
                    choice = input("Enter your choice:")
                    if choice == "1":
                        doctor.view_appointment()
                    elif choice == "2":
                        doctor.write_perceptions()
                    elif choice == "3":
                        doctor.recommend_test()
                    elif choice == "4":
                        break
                    else:
                        print("Invalid Choice")
                break
            else:
                print("Invalid login")

    # Lab / pharmacy login
    elif choice == "4":
        username = input("Enter username")
        password = input("Enter password")
        if lab.username == username and lab.password == password:
            print("Welcome Lab/Pharmacy staff!")
            # lab / pharmacy panel
            while True:
                print("\n1.View test requests \n2.Upload test reports \n3. View perceptions \n4. Mark medicine deliverd \n5. Logout")
                choice = input("Enter your choice:")
                if choice == "1":
                    lab.view_test_requests()
                elif choice == "2":
                    lab.upload_test_reports()
                elif choice == "3":
                    lab.view_perceptions()
                elif choice == "4":
                    lab.mark_medicine_deliverd()
                elif choice == "5":
                    break
                else:
                    print("Invalid Choice:")
        else:
             print("Invalid login.")

    # Exit the program
    elif choice == "5":
        print("Thank you for the using system.\n")
        print("========================")
        print("=  🌺😍 THE END 😍🌺   =")
        print("========================")
        break



    else:
         print("Invalid option")